# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.
# weight option is to set ascending numeric values.

main:
  # - name: Tour
  #   url: tour
  #   weight: 10
  - name: News
    url: post
    weight: 20
  - name: Members
    url: people
    weight: 30
  # - name: Events
  #   url: event
  #   weight: 40
  - name: Publications
    url: publication
    weight: 40
  # - name: Meeting TODO
  #   url: meeting
  #   weight: 50
  - name: Materials
    identifier: materials
    weight: 60
  - name: Challenges
    parent: materials
    url: materials/challenges/
    weight: 10 
  - name: Downloads
    parent: materials
    url: materials/downloads/
  # - name: Slides
  #   parent: materials
  #   url: materials/slides/
  # - name: Courses
  #   parent: materials
  #   url: materials/courses/
    weight: 20 
  - name: Contact
    url: contact
    weight: 70
